container:
  image: golang:1.14

env:
  GOPROXY: https://proxy.golang.org
  CODECOV_TOKEN: ENCRYPTED[64481ea00b08c4703bf350a2ad3d5a6fd7a00269576784b2943cce62604798e88f532e19fb66859fa68f43dbd4a0df15]

build_and_test_task:
  build_and_test_script:
    - apt-get update
    - apt-get install less
    - make .install.tools
    - make check
    - make vendor
    - ./hack/tree_status.sh
    - make build
    - make test
    - make build.coverage
    - make test-integration.coverage
    - make codecov
