language: go
go:
        - 1.13.x

before_script:
        - make .install.tools

script:
        - make check
        - make vendor
        - ./hack/tree_status.sh
        - make build
        - make test
