language: go
go:
        - 1.11.x
        - tip

before_script:
        - go get golang.org/x/lint/golint
        - go get github.com/LK4D4/vndr

script:
        - make check
        - make vendor
        - ./hack/tree_status.sh
        - make build
        - make test
